import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { prisma } from "../lib/prisma";
import { Vote } from "../types";
import { useEffect, useState } from "react";
import { MAX_PERSON_ID, MIN_PERSON_ID, STARWARS_API } from "../constants";
import { GetPerson, GetTwoPersons } from "./api/person";
import { getTwoIds } from "../utils/getRandomPerson";

export const getServerSideProps: GetServerSideProps = async () => {
  const votes: Vote[] = await prisma.vote.findMany();
  const { first, second } = getTwoIds();
  return {
    props: {
      votes,
      first,
      second,
    },
  };
};

const Home: NextPage = ({
  votes,
  first,
  second,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const { person: firstPerson, loading: loadingFirst } = GetPerson(first);
  const { person: secondPerson, loading: loadingSecond } = GetPerson(second);

  const loading = loadingFirst || loadingSecond;

  async function saveVote(vote: Vote) {
    const response = await fetch("/api/vote", {
      method: "POST",
      body: JSON.stringify(vote),
    });

    if (!response.ok) {
      throw new Error(response.statusText);
    }

    return await response.json();
  }

  if (loading) return <div>Loading...</div>;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {firstPerson.name} vs {secondPerson.name}
        </h1>
        <button>Vote</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
